/*
    Universidad Nacional de Costa Rica
    Sede Regional Chorotega, Campus Nicoya  
    Ingeniería en Sistemas de Información
    Programación II - EIF204
    Académica: Gloriana Peña Ramírez 

    PROYECTO PROGRAMADO - Facturación JAVA

    Desarrolladores: 
    - Eddie Alfaro 
    - Derian Abarca
    - Diego Aguilar
*/ 

package gui;

import java.sql.ResultSet;
import logica.GestionProveedor;
import logica.Proveedor;

public class frmConsultaProveedores extends javax.swing.JInternalFrame {
    
    GestionProveedor gestionProveedor;
    Proveedor proveedor;

    /**
     * Creates new form frmConsultaProveedores
     */
    public frmConsultaProveedores() {
        initComponents();
        gestionProveedor = new GestionProveedor();
        proveedor = null;
        listarProveedores();
        cboBusqueda.setEnabled(false);
        txtBusqueda.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        chkBusqueda = new javax.swing.JCheckBox();
        txtBusqueda = new javax.swing.JTextField();
        cboBusqueda = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();

        setTitle("Reporte de Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provedury_16x16.png"))); // NOI18N

        chkBusqueda.setText("Busqueda");
        chkBusqueda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBusquedaStateChanged(evt);
            }
        });
        chkBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBusquedaActionPerformed(evt);
            }
        });

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        cboBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IdProveedor", "Compañia", "Representante", "Telefono" }));
        cboBusqueda.setSelectedIndex(-1);
        cboBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBusquedaItemStateChanged(evt);
            }
        });
        cboBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBusquedaActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkBusqueda)
                .addGap(10, 10, 10)
                .addComponent(cboBusqueda, 0, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBusqueda)
                    .addComponent(cboBusqueda)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblTotal.setText("Total: 0");

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Compañia", "Contacto", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBusquedaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBusquedaStateChanged
        if (chkBusqueda.isSelected()) {
            cboBusqueda.setEnabled(true);
        } else {
            cboBusqueda.setEnabled(false);
            cboBusqueda.setSelectedIndex(-1);
            txtBusqueda.setEnabled(false);
            txtBusqueda.setText("");
            buscar();
        }
    }//GEN-LAST:event_chkBusquedaStateChanged

    private void chkBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBusquedaActionPerformed

    private void cboBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboBusquedaActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked

    }//GEN-LAST:event_tblProveedoresMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void cboBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBusquedaItemStateChanged
        if(cboBusqueda.getSelectedIndex() >= 0){
            txtBusqueda.setEnabled(true);
        }
    }//GEN-LAST:event_cboBusquedaItemStateChanged

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cboBusqueda;
    private javax.swing.JCheckBox chkBusqueda;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void listarProveedores() {
        
        gestionProveedor.conectarBD();
        ResultSet rs = gestionProveedor.listarProveedores();
        
        if (rs != null) {
            tblProveedores.setModel(gestionProveedor.cargarEnTabla(rs));
            lblTotal.setText("Total: " + tblProveedores.getRowCount());
        }
        
        gestionProveedor.desconectarBD();
    }
    
    private void buscar (){
        // ---------------  BUSQUEDA POR DEFECTO -------------//
        String sql = "SELECT * FROM tblproveedor ";

        // ------------ Se asigna variable para input text ------------ //
        String src = txtBusqueda.getText();
        
        // ----------------  BUSQUEDA ---------------- //
        // verificacion de input busqueda
        if (!src.equals("")) {
            if (chkBusqueda.isSelected()) {
                switch (cboBusqueda.getSelectedIndex()) {
                    case 0:
                        sql+="WHERE IdProveedor LIKE '"+src+"%'";
                        break;
                    case 1:
                        sql+="WHERE compañia LIKE '"+src+"%'";
                        break;
                    case 2:
                        sql+="WHERE representante LIKE '"+src+"%'";
                        break;
                    case 3:
                        sql+="WHERE telefono LIKE '"+src+"%'";
                        break;
                    default:
                        break;
                }
            }
        }
        
        gestionProveedor.conectarBD();
        ResultSet rs = gestionProveedor.seleccionar(sql);
        if (rs!=null) {
            tblProveedores.setModel(gestionProveedor.cargarEnTabla(rs));
            lblTotal.setText("Total: " + tblProveedores.getRowCount());
        }
    }
}
