/*
    Universidad Nacional de Costa Rica
    Sede Regional Chorotega, Campus Nicoya  
    Ingeniería en Sistemas de Información
    Programación II - EIF204
    Académica: Gloriana Peña Ramírez 

    PROYECTO PROGRAMADO - Facturación JAVA

    Desarrolladores: 
    - Eddie Alfaro 
    - Derian Abarca
    - Diego Aguilar
*/ 

package gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.GestionUsuario;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    GestionUsuario gestionUsuario;
    
    public frmPrincipal() {
        initComponents();
        gestionUsuario = new GestionUsuario();
        String id = txtid.getText();
        txtid.setVisible(false);

        
        //Código para poner icono personalizado al JFrame frmPrincipal
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/company.png"));
        this.setIconImage(icon.getImage());
        
        //Código para que el formulario principal inicie maximizado como MDI
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. ahao86yfrtudterdtfiygijo
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        mnu = new javax.swing.JMenuBar();
        mnuCategorias = new javax.swing.JMenu();
        mnuCategoriaGestion = new javax.swing.JMenuItem();
        mnuCategoriaReporte = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        mnuProveedoresGestion = new javax.swing.JMenuItem();
        mnuProveedoresReporte = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mnuProductosGestion = new javax.swing.JMenuItem();
        mnuProductosReporte = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuClientesGestion = new javax.swing.JMenuItem();
        mnuClientesReporte = new javax.swing.JMenuItem();
        mnuFacturacion = new javax.swing.JMenu();
        mnuFacturacionGestion = new javax.swing.JMenuItem();
        mnuFacturacionReporte = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuVentasReporte = new javax.swing.JMenuItem();
        mnuVentasIngresosReporte = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuUsuariosGestion = new javax.swing.JMenuItem();
        mnuUsuariosReporte = new javax.swing.JMenuItem();
        mnuVentana = new javax.swing.JMenu();
        mnuVentanaCerrar = new javax.swing.JMenu();
        mnuVentanaCerrarActual = new javax.swing.JMenuItem();
        mnuVentanaCerrarTodas = new javax.swing.JMenuItem();
        mnuVentanaCascada = new javax.swing.JMenuItem();
        mnuVentanaParalelo = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyudaDocumentacion = new javax.swing.JMenuItem();
        mnuAyudaContenido = new javax.swing.JMenuItem();
        mnuAyudaAcercaDe = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuSalirSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppEmpresa S.A");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblusuario.setText("Usuario: ");

        txtuser.setToolTipText("Nombre de Usuario");
        txtuser.setEnabled(false);

        txtid.setEditable(false);
        txtid.setToolTipText("ID Usuario");
        txtid.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblusuario)
                .addGap(2, 2, 2)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 203, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnuCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/category_32x32.png"))); // NOI18N
        mnuCategorias.setText("Categorias");

        mnuCategoriaGestion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuCategoriaGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/category_16x16.png"))); // NOI18N
        mnuCategoriaGestion.setText("Gestión Categorías");
        mnuCategoriaGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriaGestionActionPerformed(evt);
            }
        });
        mnuCategorias.add(mnuCategoriaGestion);

        mnuCategoriaReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuCategoriaReporte.setText("Reporte Categorías");
        mnuCategorias.add(mnuCategoriaReporte);

        mnu.add(mnuCategorias);

        mnuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provedury_32x32.png"))); // NOI18N
        mnuProveedores.setText("Proveedores");

        mnuProveedoresGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provedury_16x16.png"))); // NOI18N
        mnuProveedoresGestion.setText("Gestión Proveedores");
        mnuProveedoresGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedoresGestionActionPerformed(evt);
            }
        });
        mnuProveedores.add(mnuProveedoresGestion);

        mnuProveedoresReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuProveedoresReporte.setText("Reporte Proveedores");
        mnuProveedores.add(mnuProveedoresReporte);

        mnu.add(mnuProveedores);

        mnuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product_32x32.png"))); // NOI18N
        mnuProductos.setText("Productos");

        mnuProductosGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product_16x16.png"))); // NOI18N
        mnuProductosGestion.setText("Gestión Productos");
        mnuProductosGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosGestionActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuProductosGestion);

        mnuProductosReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuProductosReporte.setText("Reporte Productos");
        mnuProductosReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosReporteActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuProductosReporte);

        mnu.add(mnuProductos);

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client_32x32.png"))); // NOI18N
        mnuClientes.setText("Clientes");

        mnuClientesGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client_16x16.png"))); // NOI18N
        mnuClientesGestion.setText("Gestion Clientes");
        mnuClientes.add(mnuClientesGestion);

        mnuClientesReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuClientesReporte.setText("Reporte Clientes");
        mnuClientes.add(mnuClientesReporte);

        mnu.add(mnuClientes);

        mnuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill_32x32.png"))); // NOI18N
        mnuFacturacion.setText("Facturación");

        mnuFacturacionGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill_16x16.png"))); // NOI18N
        mnuFacturacionGestion.setText("Gestión Facturación");
        mnuFacturacionGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturacionGestionActionPerformed(evt);
            }
        });
        mnuFacturacion.add(mnuFacturacionGestion);

        mnuFacturacionReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuFacturacionReporte.setText("Reporte Facturación");
        mnuFacturacion.add(mnuFacturacionReporte);

        mnu.add(mnuFacturacion);

        mnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sales_32x32.png"))); // NOI18N
        mnuVentas.setText("Ventas");

        mnuVentasReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sales_16x16.png"))); // NOI18N
        mnuVentasReporte.setText("Reporte Ventas");
        mnuVentas.add(mnuVentasReporte);

        mnuVentasIngresosReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuVentasIngresosReporte.setText("Reporte Ingresos");
        mnuVentasIngresosReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasIngresosReporteActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuVentasIngresosReporte);

        mnu.add(mnuVentas);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users_32x32.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");

        mnuUsuariosGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users_16x16.png"))); // NOI18N
        mnuUsuariosGestion.setText("Gestion Usuarios");
        mnuUsuarios.add(mnuUsuariosGestion);

        mnuUsuariosReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_16x16.png"))); // NOI18N
        mnuUsuariosReporte.setText("Reporte Usuarios");
        mnuUsuariosReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosReporteActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuUsuariosReporte);

        mnu.add(mnuUsuarios);

        mnuVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/window_32x32.png"))); // NOI18N
        mnuVentana.setText("Ventana");

        mnuVentanaCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_16x16.png"))); // NOI18N
        mnuVentanaCerrar.setText("Cerrar");

        mnuVentanaCerrarActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_16x16.png"))); // NOI18N
        mnuVentanaCerrarActual.setText("Cerrar Actual");
        mnuVentanaCerrar.add(mnuVentanaCerrarActual);

        mnuVentanaCerrarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_all_16x16.png"))); // NOI18N
        mnuVentanaCerrarTodas.setText("Cerrar Todas");
        mnuVentanaCerrar.add(mnuVentanaCerrarTodas);

        mnuVentana.add(mnuVentanaCerrar);

        mnuVentanaCascada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cascade_16x16.png"))); // NOI18N
        mnuVentanaCascada.setText("En cascada");
        mnuVentana.add(mnuVentanaCascada);

        mnuVentanaParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parallel_16x16.png"))); // NOI18N
        mnuVentanaParalelo.setText("En paralelo");
        mnuVentana.add(mnuVentanaParalelo);

        mnu.add(mnuVentana);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_32x32.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        mnuAyudaDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/docs_16x16.png"))); // NOI18N
        mnuAyudaDocumentacion.setText("Documentación");
        mnuAyudaDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaDocumentacionActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAyudaDocumentacion);

        mnuAyudaContenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/issue_16x16.png"))); // NOI18N
        mnuAyudaContenido.setText("Report Issue");
        mnuAyudaContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaContenidoActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAyudaContenido);

        mnuAyudaAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about_16x16.png"))); // NOI18N
        mnuAyudaAcercaDe.setText("Acerca de...");
        mnuAyuda.add(mnuAyudaAcercaDe);

        mnu.add(mnuAyuda);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_32x32.png"))); // NOI18N
        mnuSalir.setText("Cerrar");

        mnuSalirSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signout_16x16.png"))); // NOI18N
        mnuSalirSalir.setText("Cerrar Sesión");
        mnuSalirSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSalirActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuSalirSalir);

        mnu.add(mnuSalir);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCategoriaGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriaGestionActionPerformed
        // Código para mostrar el JInternaFrame frmCategorías
        frmCategorias frmCat = new frmCategorias();
        escritorio.add(frmCat);
        frmCat.show();
        
    }//GEN-LAST:event_mnuCategoriaGestionActionPerformed

    private void mnuProductosGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosGestionActionPerformed
        // Código para mostrar el JInternaFrame frmProductos
        frmProductos frmPro;
        try {
            frmPro = new frmProductos();
            escritorio.add(frmPro);
            frmPro.show();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnuProductosGestionActionPerformed

    private void mnuSalirSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSalirActionPerformed
        try {
            // LLamando al metodo SignOut
            SignOut();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuSalirSalirActionPerformed

    private void mnuProductosReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosReporteActionPerformed
        // Código para mostrar el JInternaFrame frmProductos
        frmConsultaProductos frmCPro;
        try {
            frmCPro = new frmConsultaProductos();
            escritorio.add(frmCPro);
            frmCPro.show();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuProductosReporteActionPerformed

    private void mnuFacturacionGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturacionGestionActionPerformed
        // Código para mostrar el JInternaFrame frmFacturacion
        frmFacturacion frmfact;
        frmfact = new frmFacturacion();
        escritorio.add(frmfact);
        frmfact.show();
    }//GEN-LAST:event_mnuFacturacionGestionActionPerformed

    private void mnuVentasIngresosReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasIngresosReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVentasIngresosReporteActionPerformed

    private void mnuUsuariosReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuariosReporteActionPerformed

    private void mnuProveedoresGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedoresGestionActionPerformed
        try {
            frmProveedores frmProv;
            frmProv = new frmProveedores();
            escritorio.add(frmProv);
            frmProv.show();
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ups, algo a pasado al intentar cargar el panel de proveedores", "Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_mnuProveedoresGestionActionPerformed

    private void mnuAyudaDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaDocumentacionActionPerformed
        // TODO add your handling code here:
        try {
            String link = "https://github.com/JoeAlv/facturacion-java";
            linkWeb(link);
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ups, algo a pasado al intentar cargar la documentación", "Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_mnuAyudaDocumentacionActionPerformed

    private void mnuAyudaContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaContenidoActionPerformed
        // TODO add your handling code here: 
        try {
            String link = "https://github.com/JoeAlv/facturacion-java/issues";
            linkWeb(link);
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ups, algo a pasado al intentar cargar el reporte de problemas", "Error", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_mnuAyudaContenidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblusuario;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyudaAcercaDe;
    private javax.swing.JMenuItem mnuAyudaContenido;
    private javax.swing.JMenuItem mnuAyudaDocumentacion;
    private javax.swing.JMenuItem mnuCategoriaGestion;
    private javax.swing.JMenuItem mnuCategoriaReporte;
    private javax.swing.JMenu mnuCategorias;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuClientesGestion;
    private javax.swing.JMenuItem mnuClientesReporte;
    private javax.swing.JMenu mnuFacturacion;
    private javax.swing.JMenuItem mnuFacturacionGestion;
    private javax.swing.JMenuItem mnuFacturacionReporte;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenuItem mnuProductosGestion;
    private javax.swing.JMenuItem mnuProductosReporte;
    private javax.swing.JMenu mnuProveedores;
    private javax.swing.JMenuItem mnuProveedoresGestion;
    private javax.swing.JMenuItem mnuProveedoresReporte;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuSalirSalir;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenuItem mnuUsuariosGestion;
    private javax.swing.JMenuItem mnuUsuariosReporte;
    private javax.swing.JMenu mnuVentana;
    private javax.swing.JMenuItem mnuVentanaCascada;
    private javax.swing.JMenu mnuVentanaCerrar;
    private javax.swing.JMenuItem mnuVentanaCerrarActual;
    private javax.swing.JMenuItem mnuVentanaCerrarTodas;
    private javax.swing.JMenuItem mnuVentanaParalelo;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem mnuVentasIngresosReporte;
    private javax.swing.JMenuItem mnuVentasReporte;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    private void SignOut() throws SQLException{
        int resp = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de cerrar sesión?","Cerrar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(resp == JOptionPane.YES_OPTION) {
            frmLogin login;
            gestionUsuario.login_log("El usuario " + txtuser.getText() + " ha cerrado session.", txtid.getText());
            login = new frmLogin();
            login.setVisible(true);
            this.dispose();
        }
    }    
    
    public void linkWeb(String url) {
        Desktop enlace = Desktop.getDesktop();
        try {
            enlace.browse(new URI(url));
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
